import { GetStaticProps } from "next";
import Head from "next/head";
import React from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import { categories, data } from "../data/reports";
import styles from "../styles/Home.module.css";

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      data,
      categories,
    },
  };
};

const Home = (): JSX.Element => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <BarChart
          layout="vertical"
          width={500}
          height={300}
          data={data}
          margin={{
            top: 20,
            right: 30,
            left: 20,
            bottom: 5,
          }}
        >
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis type="number" unit="h" />
          <YAxis dataKey="name" type="category" />
          <Tooltip />
          <Legend />
          {categories.map((category) => (
            <Bar
              dataKey={category.title}
              stackId="project"
              fill={category.color}
            />
          ))}
        </BarChart>
      </main>
    </div>
  );
};

export default Home;
